[tool.poetry]
name = "presentation-rag"
version = "0.1.0"
description = "Presentation RAG Raft Internship"
authors = ["Ilia Tambovtsev <ilia.tambovtsev@raftds.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter-data-science = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
